####################################################################################
# docker-compose file for TrustBuilder Training Labs
# v2.0 - 2024.03 - BRO
#
# Trustbuilder docker compose file for training labs
# Using docker compose it will:
#
# - create a network 'guacamole_network' with the 'bridge' driver.
# - create a service 'guacd' from 'guacamole/guacd' connected to 'guacamole_network'
# - create a service 'postgres' from 'postgres' connected to 'guacamole_network'
# - create a service 'guacamole' from 'guacamole/guacamole/' conn. to 'guacamole_network'
# - create a service 'nginx' from 'nginx' connected to 'guacamole_network'
# - create a service 'ldap' from 'rroemhild/test-openldap' connected to 'guacamole_network'
# - create a service 'ldapproxy' from Dockerfile connected to 'guacamole_network'
#
# Uncomment and configure relative following LAB sections
# and then stop and restart with :
#
# docker compose down && docker compose up -d 
#
# The initial (default) login for the guacamole webinterface is:
#
#     Username: guacadmin
#     Password: guacadmin
#
#####################################################################################

x-config: &config
    #---------------------
    # LAB RADIUS
    #---------------------
    #RADIUS_HOSTNAME: radius-a.myinwebo.com
    RADIUS_AUTH_PORT: 1812
    RADIUS_SHARED_SECRET: secret
    RADIUS_AUTH_PROTOCOL: pap
    RADIUS_RETRIES: 6
    RADIUS_TIMEOUT: 10
    RADIUS_TRUST_ALL: true

    #---------------------
    # LAB OpenID Connect
    #---------------------
    #OPENID_AUTHORIZATION_ENDPOINT: https://connect.myinwebo.com/<YOUR_CONNECTOR_ALIAS>/authorize
    OPENID_JWKS_ENDPOINT: https://connect.myinwebo.com/<YOUR_CONNECTOR_ALIAS>/jwks
    OPENID_ISSUER: https://connect.myinwebo.com/<YOUR_CONNECTOR_ALIAS>/
    OPENID_CLIENT_ID: guac
    OPENID_REDIRECT_URI: https://localhost/
    
    #---------------------
    # LAB SAML
    #---------------------
    #SAML_IDP_METADATA_URL: https://www.myinwebo.com/console/<YOUR_SAML_METADATA>
    #SAML_ENTITY_ID: https://localhost/
    SAML_CALLBACK_URL: https://localhost/
    SAML_STRICT: false
    SAML_COMPRESS_REQUEST: true
    SAML_COMPRESS_RESPONSE: false
    SAML_DEBUG: true

    #---------------------
    # LAB ldap proxy
    #---------------------
    LDAP_HOSTNAME: 10.99.1.1
    LDAP_PORT: 389
    LDAP_ENCRYPTION_METHOD: none
    LDAP_MAX_SEARCH_RESULTS: 1000
    LDAP_SEARCH_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
    LDAP_SEARCH_BIND_PASSWORD: 'GoodNewsEveryone'
    LDAP_USER_BASE_DN: 'ou=people,dc=planetexpress,dc=com'
    LDAP_USERNAME_ATTRIBUTE: 'uid'
    LDAP_USER_SEARCH_FILTER: (objectClass=*)
    LDAP_OPERATION_TIMEOUT: 10

    #---------------------
    # Authentication order
    #---------------------
    # You can change order or force an authentication provider
    # Provide only one EXTENSION_PRIORITY line
    #---------------------
    EXTENSION_PRIORITY: "postgresql,ldap,radius,openid,saml"   
    # Use only configured ldap to authenticate
    #EXTENSION_PRIORITY: "ldap"
    
# create a network 'guacamole_network' in mode 'bridged'
networks:
  guacamole_network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.99.1.0/24

services:
#----------------------------------------      
# guacamole daemon (guacd)
#----------------------------------------      
  guacd:
    container_name: guacd
    image: guacamole/guacd:1.5.4
    networks:
      guacamole_network:
    restart: always
    #volumes:
    #- ./drive:/drive:rw
    #- ./record:/record:rw

#----------------------------------------      
# postgres
#----------------------------------------      
  postgres:
    container_name: postgres
    environment:
      TZ: Europe/Paris
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      guacamole_network:
    restart: always
    volumes:
    - ./.hide/init:/docker-entrypoint-initdb.d:z
    - ./.hide/data:/var/lib/postgresql/data:Z
    ports:
    - 5432:5432

#----------------------------------------      
# nginx
#----------------------------------------      
  nginx:
   container_name: nginx
   restart: always
   image: nginx
   volumes:
   - ./.hide/nginx/templates:/etc/nginx/templates:ro
   - ./.hide/nginx/ssl/self.cert:/etc/nginx/ssl/self.cert:ro
   - ./.hide/nginx/ssl/self-ssl.key:/etc/nginx/ssl/self-ssl.key:ro
   ports:
   - 443:443
   links:
   - guacamole
   networks:
     guacamole_network:

#----------------------------------------      
# ldap_server
#----------------------------------------      
  ldap_server:
    image: rroemhild/test-openldap
    container_name: ldap_server
    hostname: ldap
    restart: on-failure
    networks:
       guacamole_network:
    labels:
      org.label-schema.group: "ldap-server"
    ports:
      - "389:10389"
      - "636:10636"
    volumes:
      - ./.hide/ldap:/ldap:rw
      
#----------------------------------------      
# ldap_proxy
#----------------------------------------      
  ldap_proxy:
    image: trustbuilder/ldap_proxy:1.6.1
    container_name: ldap_proxy
    hostname: ldapproxy
    # comment next line for NO users authentications in logs
    command: sh -c "cd /ldap-proxy-1.6.1/bin && ./run.sh -verbose"
    environment:
      TZ: Europe/Paris
    build:
      context: .
    networks:
      guacamole_network:
    ports:
      - 10389:389
      - 10636:636
    volumes:
      - ./ldapproxy:/ldap-proxy-1.6.1/config:rw
      - ./ldapproxy/logs:/ldap-proxy-1.6.1/logs
      
#----------------------------------------      
# guacamole
#----------------------------------------      
  guacamole: 
    container_name: guacamole
    image: guacamole/guacamole:1.5.4
    depends_on:
    - guacd
    - postgres
    links:
    - guacd
    networks:
      guacamole_network:
    volumes:
      - ./.hide/guacamole:/guacamolehome:rw
    ports:
    - 8080/tcp
    restart: always    
    environment:
      <<: *config
      TZ: Europe/Paris
      GUACD_HOSTNAME: guacd
      #---------------------------
      # Default DB Authentication
      #---------------------------
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRESQL_USER: guacamole_user
      GUACAMOLE_HOME: /guacamolehome
      LOGBACK_LEVEL: info

